<?php
/**
 * This HTML controller is what generates HTML pages (as opposed to JSON responses
 * generated by the other controllers).  The reason is testability: most of the 
 * manager app can be tested by $scriptProperties in, JSON out.  The HTML pages
 * generated by this controller end up being static HTML pages (well... ideally, 
 * anyway). 
 *
 * See http://stackoverflow.com/questions/10941249/separate-rest-json-api-server-and-client
 *
 * See the IndexManagerController class (index.class.php) for routing info.
 *
 * @package assman
 */
namespace Taxonomies;
class PageController extends BaseController {

    public $loadHeader = true;
    public $loadFooter = true;
    // GFD... this can't be set at runtime. See improvised addStandardLayout() function
    public $loadBaseJavascript = true; 
    // Stuff needed for interfacing with Assman API (mapi)
    public $client_config = array();
    public $tax;
    function __construct(\modX &$modx,$config = array()) {
        parent::__construct($modx,$config);
        static::$x =& $modx;

        $this->config['controller_url'] = self::url();
        $this->config['core_path'] = $this->modx->getOption('taxonomies.core_path', null, MODX_CORE_PATH.'components/taxonomies/');
        $this->config['assets_url'] = $this->modx->getOption('taxonomies.assets_url', null, MODX_ASSETS_URL.'components/taxonomies/');
        $this->modx->regClientCSS($this->config['assets_url'] . 'css/taxonomies.css');
        $this->modx->regClientCSS($this->config['assets_url'] . 'css/bootstrap.css'); 
        $this->modx->regClientCSS('https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.css');



        $this->modx->regClientStartupScript($this->config['assets_url'] . 'js/jquery.min.js');
        $this->modx->regClientStartupScript($this->config['assets_url'] . 'js/bootstrap.js');
        $this->modx->regClientStartupScript($this->config['assets_url'] . 'js/handlebars-v2.0.0.js');
        $this->modx->regClientStartupScript($this->config['assets_url'].'js/taxonomies.js');
        $this->tax = new Base($this->modx);

    }

    /**
     * getBreadcrumbs
     * @param array $scriptProperties
     * @return html markup
     */
    public function getBreadcrumbs(array $scriptProperties = array()) {
        $this->loadHeader = false;
        $this->loadFooter = false;
        // GFD... this can't be set at runtime. See improvised addStandardLayout() function
        $this->loadBaseJavascript = false;

        $items = $this->tax->getBcRecords($scriptProperties);
        $last = array_pop($items);

        $this->setPlaceholder('links', $items);
        $this->setPlaceholder('last', $last['pagetitle']);
        return $this->fetchTemplate('main/breadcrumbs.php');
    }
    
    //------------------------------------------------------------------------------
    //! Index
    //------------------------------------------------------------------------------
    /**
     * @param array $scriptProperties
     */
    public function getIndex(array $scriptProperties = array()) {
        $this->modx->log(\modX::LOG_LEVEL_INFO, print_r($scriptProperties,true),'','Taxonomies PageController:'.__FUNCTION__);

        $connectors['connector_url'] = utf8_encode($this->tax->getControllerUrl());
        $this->addHtml('
            <script type="text/javascript">
                 var taxonomies = '.json_encode($connectors).';
            </script>');
        $this->setPlaceholder('loader', $this->config['assets_url'] . 'images/ajax-loader.GIF');
        $this->setPlaceholder('taxonomies',$this->tax->getTaxonomies());
        return $this->fetchTemplate('main/index.php');
    }

    /**
     *
     * getTerms
     *
     * @param array $scriptProperties
     * @return json
     */
    public function getTerms(array $scriptProperties = array()) {
        $this->loadHeader = false;
        $this->loadFooter = false;
        // GFD... this can't be set at runtime. See improvised addStandardLayout() function
        $this->loadBaseJavascript = false;
        $id = $this->modx->getOption('page_id',$scriptProperties);
        $terms =  $this->tax->getTerms($id);
        return json_encode($terms);
    }


        
}
/*EOF*/